language: php

sudo: false

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.php-cs-fixer

matrix:
    include:
        - php: 5.5
          env: deps=low
          services:
              - docker
        - php: 5.6
          services:
              - docker
        - php: 7.0
          services:
              - docker
        - php: 7.1
          services:
              - docker
        - php: 7.2
          env: deps=high CS=true
          services:
              - docker

before_install:
    - stty cols 120
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - if [[ $deps = high ]]; then composer update --no-interaction --no-progress --ansi; fi
    - if [[ $deps = low ]]; then composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable; fi
    - if [[ ! $deps ]]; then composer install --no-interaction --no-progress --ansi; fi
    - ./tests/setup.sh
    - mkdir -p "$HOME/.php-cs-fixer"

script:
    - ./tests/run.sh
    - if [[ "$CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

notifications:
    email: false
